type Vault @entity(immutable: false) {
  id: ID!
  address: Bytes!
  portfolioAddress: Bytes
  owner: Bytes
  executor: Bytes
  createdAtBlock: BigInt!
  createdAtTimestamp: BigInt!
  createdTxHash: Bytes!
  eventCount: BigInt!
}

type VaultEvent @entity(immutable: true) {
  id: ID! # txHash-logIndex
  vault: Vault!
  eventName: String!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  txHash: Bytes!
  logIndex: BigInt!

  # optional normalized fields for common events
  token: Bytes
  tokenIn: Bytes
  tokenOut: Bytes
  amountIn: BigInt
  amountOut: BigInt
}
